<div class = " sub-banner02" >

<div class = "Block01" style="float: left">

  <a href="<?=$block->getData('url1')?>">  <img src="<?=$block->getData('hinh1')?>" style="width: 600px;height: 300px"/></a>

</div>

<div class = "Block01" style ="float:left">
  <a href = "<?=$block->getData('url2')?>">  <img src="<?=$block->getData('hinh2')?>" style="width: 600px;height: 300px"/> </a>

</div>

</div>

<style>
    .Block
    {
        padding: 5px;
    }

    .sub-banner02 {
        display: flex;
        justify-content: space-around;

    }
</style>



