
<div class="announcement">

    <div class="announcement-content">
    <a href="<?php echo $block->getData('link1'); ?>" class="announcement-item-link">
             <div class="announcement-item-icon">
                <img src="<?=$block->getData('hinh1')?>">
             </div>
          <div class="announcement-item-title">
            <?php echo $block->getData('notice1'); ?>
          </div>
</a>
    </div>


    <div class="announcement-content">
    <a href="<?php echo $block->getData('link2'); ?>" class="announcement-item-link">
             <div class="announcement-item-icon">
                <img src="<?=$block->getData('hinh2')?>">
             </div>
          <div class="announcement-item-title">
            <?php echo $block->getData('notice2'); ?>
          </div>
</a>
    </div>

    <div class="announcement-content">
    <a href="<?php echo $block->getData('link3'); ?>" class="announcement-item-link">
             <div class="announcement-item-icon">
                <img src="<?=$block->getData('hinh3')?>">
             </div>
          <div class="announcement-item-title">
            <?php echo $block->getData('notice3'); ?>
          </div>
</a> 
    </div>


</div>
<style>


.announcement {
    display: flex;
    margin-top: 20px;
    border-top: 1px solid #333;
    border-bottom: 1px solid #333;
    }
    
    .announcement-content {
    width: 33.33%;
    
    .announcement-item-link {
    text-decoration: none;
    color: #333;
    }

    }
    
    .announcement-item-icon {
    width: 35px;
    margin: 20px auto -15px;
    height: 35px
    }
    
    .announcement-item-title {
    text-align: center;
    padding: 20px 20px;
    margin: 0 3px 0 3px;
    }

    </style>
